In [2]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

<h1>recomendacion_juego</h1>

def recomendacion_juego( id de producto ): Ingresando el id de producto, deberíamos recibir una lista con 5 juegos recomendados similares al ingresado.

In [3]:
# Cargamos el archivo CSV a utilizar:
games_df = pd.read_csv(r"..\Archivos Producidos\games.csv")

games_df.dtypes

app_name                     object
release_year                  int64
item_id                       int64
developer                    object
Action                        int64
Adventure                     int64
Animation &amp; Modeling      int64
Audio Production              int64
Casual                        int64
Design &amp; Illustration     int64
Early Access                  int64
Education                     int64
Free to Play                  int64
Indie                         int64
Massively Multiplayer         int64
Photo Editing                 int64
RPG                           int64
Racing                        int64
Simulation                    int64
Software Training             int64
Sports                        int64
Strategy                      int64
Utilities                     int64
Video Production              int64
Web Publishing                int64
dtype: object

In [4]:
# Seleccionamos las columnas que nos serán de utilidad:
df_recom_game = games_df[['item_id', 'Action',
       'Adventure', 'Animation &amp; Modeling', 'Audio Production', 'Casual',
       'Design &amp; Illustration', 'Early Access', 'Education',
       'Free to Play', 'Indie', 'Massively Multiplayer', 'Photo Editing',
       'RPG', 'Racing', 'Simulation', 'Software Training', 'Sports',
       'Strategy', 'Utilities', 'Video Production', 'Web Publishing']]

df_recom_game.head()

,item_id,Action,Adventure,Animation &amp; Modeling,Audio Production,Casual,Design &amp; Illustration,Early Access,Education,Free to Play,...,Photo Editing,RPG,Racing,Simulation,Software Training,Sports,Strategy,Utilities,Video Production,Web Publishing
0,761140,1,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
1,643980,0,0,0,0,0,0,0,0,1,...,0,1,0,0,0,0,1,0,0,0
2,670290,0,0,0,0,1,0,0,0,1,...,0,0,0,1,0,1,0,0,0,0
3,767400,1,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,772540,1,1,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

Una vez ya filtrado del DataFrame, creamos el modelo de recomendación:

In [5]:
def recomendacion_juego(item_id):

    # Obtenemos la fila correspondiente al juego dado por "item_id":
    juego = df_recom_game[df_recom_game["item_id"] == item_id].iloc[:, 1:]

    # Excluímos el juego del DataFrame antes de calcular la similitud (evitamos que el modelo nos recomiende el mismo juego):
    df_sin_juego = df_recom_game[df_recom_game["item_id"] != item_id]

    # Calculamos la similitud de coseno entre el juego y todos los demás juegos:
    similitudes = cosine_similarity(juego, df_sin_juego.iloc[:, 1:])

    # Convertimos las similitudes en un DataFrame:
    similitudes_df = pd.DataFrame(similitudes.flatten(), columns=["similitud"])

    # Encontramos los 5 juegos más similares:
    juegos_similares = df_sin_juego.loc[similitudes_df.sort_values(by="similitud", ascending=False).index[:5], "item_id"]

    # Devolvemos el resultado final:
    return list(juegos_similares)

In [6]:
# Probamos el modelo:
print(recomendacion_juego(497520))
print(recomendacion_juego(717130))
print(recomendacion_juego(111400))

[719920, 403030, 718290, 718150, 717130]
[718290, 718150, 466770, 280680, 659710]
[414720, 522040, 280930, 662390, 348810]

Guardamos el DataFrame utilizado:

In [7]:
# Guardamos el dataframe "df_recom_game":
df_recom_game.to_csv(r"..\Archivos Producidos\Data para Endpoints\df_recom_game.csv", index=False)